#**Ejercicios de práctica NumPy y pandas**
###Del arreglo al DataFrame

##**A. Crear e inspeccionar arreglos**

#### 1.  Importar la biblioteca

##### *Complete la importación con el alias convencional de la comunidad.* texto en cursiva

In [ ]:
import numpy as np
print(np.__version__)


2.1.3


#### 2.  Del listado al arreglo

##### *Convierta la lista de precios en un arreglo de NumPy.*

In [ ]:
precios = np.array([24000, 28000, 22000, 30000, 8000])

print(type(precios).__name__)
print(precios.dtype)

#print(type(precios))

ndarray
int64


#### 3.   Los tres atributos

##### *Averigüe la forma, el número de dimensiones y la cantidad de elementos.*

In [ ]:
matriz = np.array([[2, 4000],
                  [1, 2800],
                  [3, 2200]])

print(matriz.shape)
print(matriz.ndim)
print(matriz.size)



(3, 2)
2
6


#### 4.  Secuencias automáticas

##### *Genere una secuencia con paso fijo, otra con extremos fijos y un arreglo de ceros.*

In [ ]:
secuencia = np.arange(0, 10, 2)
rango = np.linspace(0, 1, 5)
ceros = np.zeros(5)


print(secuencia)
print(rango)
print(ceros.dtype)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
float64


#### 5.  Corrección: falta algo

##### *Este bloque lanza TypeError: array() takes from 1 to 2 positional arguments but 3 were given.*

In [ ]:
#precios = np.array(24000, 28000, 22000)

precios = np.array([24000, 28000, 22000])

##### ***Respuesta:*** *Es por que no tenian corchete los cuales definen la estructura*

##**B. Vectorización y broadcasting**

#### 6.  Multiplicar dos arreglos

##### *Calcule el ingreso de cada transacción multiplicando elemento por elemento.*

In [ ]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])
ingresos = cantidades * precios
print(ingresos)

[48000 28000 66000 60000  8000]


#### 7.  El escalar se estira

##### *Aplique un descuento del diez por ciento a todos los precios.*

In [ ]:
con_descuento = precios * 0.9
print(con_descuento)
print(con_descuento.dtype)

[21600. 25200. 19800. 27000.  7200.]
float64


#### 8.  El mismo cálculo, dos formas

##### *Escriba con NumPy lo que el ciclo hace con listas.*

In [ ]:
# con listas de Python
lista = ([24000, 28000, 22000, 30000, 8000])
resultado = []
for p in lista:
    resultado.append(p * 1.19)
print(f"Resultado Python:{resultado}")


# con NumPy, en una sola línea
lista = np.array([24000, 28000, 22000, 30000, 8000])
resultado_np = lista*1.19
print(f"Resultado Numpy:{resultado_np}")

Resultado Python:[28560.0, 33320.0, 26180.0, 35700.0, 9520.0]
Resultado Numpy:[28560. 33320. 26180. 35700.  9520.]


#### 9.  Predicción: lista o arreglo

##### *El mismo operador sobre dos estructuras distintas.*

In [ ]:
lista = [1, 2, 3]
arreglo = np.array([1, 2, 3])

print(lista * 2)
print(arreglo * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


##### ***Respuesta:***
#####*-Para la lista lo que esta haciendo es duplicar los valores de la lista*
#####*-Para el areglo esta multiplicando cada valor de la lista por 2*

#### 10.  Predicción: formas distintas

##### *Un arreglo de cinco elementos multiplicado por uno de cuatro.*

In [ ]:
a = np.array([2, 1, 3, 2, 1])
b = np.array([10, 20, 30, 40])

print(a * b)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

##### ***Respuesta:*** *Arroja un error debido al tamaño de cada lista , la primera contiene 5 elementos y la segunda 4*

#### 11.  Corrección: el ciclo sobra

##### *El bloque funciona, pero desaprovecha NumPy por completo*

In [ ]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])

ingresos = np.zeros(5)
for i in range(5):
    ingresos[i] = cantidades[i] * precios[i]

print(f"Resultado con ciclo:{ingresos}")

ingresos = cantidades * precios
print(f"Resultado Numpy:{ingresos}")

Resultado con ciclo:[48000. 28000. 66000. 60000.  8000.]
Resultado Numpy:[48000 28000 66000 60000  8000]


##### ***Respuesta:*** *Aparte de no tener que escribir mas codigo, se puede hacer la operación mas directa y corre mas rapido*

##**C.  Indexación, rebanado y máscaras**

#### 12.  Primero, último y una porción

##### *Obtenga elementos por posición sin contar cuántos hay.*

In [ ]:
precios = np.array([24000, 28000, 22000, 30000, 8000])

print(precios[0])     # el primero
print(precios[-1])     # el último
print(precios[1:4])     # las posiciones 1, 2 y 3

24000
8000
[28000 22000 30000]


#### 13.   La máscara booleana

##### *Construya la condición y úsela para filtrar.*

In [ ]:
precios = np.array([24000, 28000, 22000, 30000, 8000])

mascara = precios > 20000

print(mascara)
print(precios[mascara])
print(precios[mascara].sum())

[ True  True  True  True False]
[24000 28000 22000 30000]
104000


#### 14.   Dos condiciones a la vez

##### *Precios mayores a 10.000 y menores a 29.000. Recuerde el operador correcto*

In [ ]:
seleccion = precios[(precios > 10000) & (precios < 29000)]

print(seleccion)

[24000 28000 22000]


#### 15.   Etiquetar según una condición

##### *Clasifique cada precio sin escribir un ciclo ni un if.*

In [ ]:
etiquetas = np.where(precios > 25000, "alto", "normal")

print(etiquetas)

['normal' 'alto' 'normal' 'alto' 'normal']


#### 16.   Contar y sumar lo filtrado

##### *Cuántos elementos cumplen la condición y cuánto suman.*

In [ ]:
caros = precios[precios > 20000]

print(caros.size)      # cuántos son
print(caros.sum())    # cuánto suman

4
104000


#### 17. Corrección: el operador equivocado

##### *Este bloque lanza ValueError: The truth value of an array with more than one element is ambiguous.*

In [ ]:
#seleccion = precios[(precios > 10000) and (precios < 29000)]

seleccion = precios[(precios > 10000) & (precios < 29000)]

print(seleccion)

[24000 28000 22000]


##### ***Respuesta:*** *Por que no se usa and se debe usar &*

##**D.  Agregar y resumir**

#### 18. Las funciones de resumen

##### *Complete cada línea con el método que corresponde.*

In [ ]:
ingresos = np.array([48000, 28000, 66000, 60000, 8000])

print(ingresos.sum())
print(ingresos.mean())
print(ingresos.max())
print(round(ingresos.std(), 2))

210000
42000.0
66000
21391.59


#### 19. Sumar por columna

##### *Cada fila es un producto y cada columna una sede. Obtenga el total de cada sede.*

In [ ]:
matriz = np.array([[48000, 28000],
                   [66000, 60000],
                   [ 8000, 12000]])

print(matriz.sum(axis=0))

[122000 100000]


#### 20. Sumar por fila y en total

##### *Ahora el total de cada producto y el total general.*

In [ ]:
print(matriz.sum(axis=1))
print(matriz.sum())

[ 76000 126000  20000]
222000


#### 21. Predicción: el eje que confunde

##### *Sin ejecutar nada todavía, escriba su predicción y después compruébela*

In [ ]:
print(matriz.mean(axis=0))

[40666.66666667 33333.33333333]


##### ***Respuesta:*** *Devuelve 2 por que esta haciendo el promedio de cada sede, es decir cada columna*

##**D.  Agregar y resumir**

In [ ]:
import pandas as pd

df_ventas = pd.read_csv ("datos_ventas.csv", sep =";") #ncoding="latin" (Para reconocer tildes)
df_ventas.head()

,fecha,cliente,producto,categoria,cantidad,precio_unitario,costo_unitario,sede
0,3/08/2026,101,Bowl Andino,Almuerzo,2,"24.000,00","14.000,00",centro
1,3/08/2026,102,Pasta Urbana,Almuerzo,1,"28.000,00","17.000,00",NORTE
2,4/08/2026,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
3,4/08/2026,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
4,4/08/2026,104,Hamburguesa Central,Cena,2,"30.000,00","19.000,00",Norte


#### 22.  Crear e inspeccionar el DataFrame

##### *Convierta la lista de diccionarios del caso en una tabla y revise su estructura.*

In [ ]:
import pandas as pd

df_ventas = pd.read_csv("datos_ventas.csv", sep=";")
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"], format="mixed")

print(df_ventas.shape)
print(df_ventas.head(3))

(19, 8)
       fecha  cliente      producto categoria  cantidad precio_unitario  \
0 2026-03-08      101   Bowl Andino  Almuerzo         2       24.000,00   
1 2026-03-08      102  Pasta Urbana  Almuerzo         1       28.000,00   
2 2026-04-08      103   Bowl Andino  Almuerzo         1       24.000,00   

  costo_unitario     sede  
0      14.000,00   centro  
1      17.000,00    NORTE  
2      14.000,00  Centro   


#### 23.  Una columna o varias

##### *Complete los corchetes para obtener primero una Series y después un DataFrame.*

In [ ]:
una = df_ventas["producto"]
varias = df_ventas[["producto", "cantidad"]]
print(type(una).__name__, type(varias).__name__)

Series DataFrame


#### 24.  Predicción: qué hay debajo de una columna
##### *pandas está construido sobre NumPy. Compruébelo.*

In [ ]:
arreglo = df_ventas["cantidad"].to_numpy()
print(type(arreglo).__name__)
print(arreglo.sum())


ndarray
32


#### 25.  Predicción: el rango que no se comporta igual
##### *Dos formas de localizar filas, dos resultados distintos.*

In [ ]:
print(df_ventas.loc[0:2].shape[0])
print(df_ventas.iloc[0:2].shape[0])

3
2


##**F.  Filtrar, derivar y agrupar**

#### 26.  Filtrar con dos condiciones
##### Almuerzos de la sede Centro. Cada comparación va entre paréntesis.

In [ ]:
mascara = (
    (df_ventas["sede"] == "Centro")
    & (df_ventas["categoria"] == "Almuerzo")
)

seleccion = df_ventas.loc[mascara].copy()

print(seleccion.shape[0], seleccion["cantidad"].sum())

3 7


#### 27.  Columnas derivadas  
##### Cree las tres columnas que permiten hablar de rentabilidad.

In [ ]:
df_ventas["ingreso"] = df_ventas["cantidad"] * df_ventas["precio_unitario"]
df_ventas["costo_total"] = df_ventas["cantidad"] * df_ventas["costo_unitario"]
df_ventas["margen_bruto"] = df_ventas["ingreso"] - df_ventas["costo_total"]

print(df_ventas["ingreso"].sum(), df_ventas["margen_bruto"].sum())

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
print(df_ventas[["cantidad", "precio_unitario", "costo_unitario"]].dtypes)

cantidad            int64
precio_unitario    object
costo_unitario     object
dtype: object


#### 28.  Indicadores globales
##### El porcentaje se calcula después de sumar, no antes.

In [ ]:
ingreso_total = df_ventas["ingreso"].sum()
margen_total = df_ventas["margen_bruto"].sum()

porcentaje_global = round(margen_total / ingreso_total * 100, 2)

ticket_promedio = round(ingreso_total / len(df_ventas), 2)

print(porcentaje_global, ticket_promedio)

KeyError: 'margen_bruto'

#### 29.  Agrupar por producto
##### Construya la tabla de indicadores y observe el resultado antes de responder.

In [ ]:
kpi = (
    df_ventas
    .groupby("producto")
    .agg(
        ingreso=("ingreso", "sum"),
        margen=("margen_bruto", "sum"),
    )
    .reset_index()
)

kpi["porcentaje_margen"] = (kpi["margen"] / kpi["ingreso"] * 100).round(2)
print(kpi)

KeyError: "Column(s) ['margen_bruto'] do not exist"

#### 30.  Reto integrador: el resumen ejecutivo
##### Encapsule el análisis en una función que reciba el DataFrame y no dependa de ninguna variable global. Después aplíquela solo a la sede Centro.

In [ ]:
def resumen_ejecutivo(df):
    ingreso = df["ingreso"].sum()
    margen = df["margen_bruto"].sum()
    return {
        "total_ingresos": ingreso,
        "margen_bruto": margen,
        "porcentaje_margen": round(margen / ingreso * 100, 2),
        "ticket_promedio": round(ingreso / len(df), 2),
    }

print(resumen_ejecutivo(df_ventas))

solo_centro = df_ventas[df_ventas["sede"] == "Centro"].copy()
print(resumen_ejecutivo(solo_centro))

KeyError: 'margen_bruto'