#Ejercicios en clase replicando codigo de pptx compartido
### Presentación Numpy Pandas

##**Diapositiva 2**

###**Del ciclo al arreglo: por que Numpy**
#####Una lista de Python guarda objetos sueltos; un arreglo de NumPy guarda números del mismo tipo, uno junto a otro.

#####Con listas de Python

In [ ]:
precios = [24000,28000,22000,30000,8000]

con_iva=[]
for p in precios:
  con_iva.append (p* 1.19)

print(con_iva)
print(precios)

[28560.0, 33320.0, 26180.0, 35700.0, 9520.0]
[24000, 28000, 22000, 30000, 8000]


#####Con arreglos Numpy

In [ ]:
import numpy as np

precios = np.array(
    [24000, 28000, 22000, 30000, 8000]
)

con_iva= precios * 1.19

print(con_iva)
print(precios)

[28560. 33320. 26180. 35700.  9520.]
[24000 28000 22000 30000  8000]


##**Diapositiva 3**

###**Crear e inspeccionar arreglos**
#####Cuatro formas de construirlos y tres atributos que describen cualquier arreglo.

In [ ]:
import numpy as np

precios = np.array([24000,28000,22000,30000,8000])
ceros = np.zeros (5)
secuencia = np.arange (0,10,2)
rango = np.linspace (0,1,5)

matriz = np.array ([[2,24000],
                    [1,28000],
                    [3,22000]])

print(ceros)
print(secuencia)
print(rango)

[0. 0. 0. 0. 0.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


##**Diapositiva 4**

###**Operaciones vectorizadas y broadcasting**
#####Dos arreglos de la misma forma operan elemento por elemento; un escalar se estira para alcanzar a todos.

In [ ]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])

ingresos = cantidades * precios
con_descuento = precios * 0.9
total = ingresos.sum()

print(ingresos)
print(con_descuento)
print(total)

[48000 28000 66000 60000  8000]
[21600. 25200. 19800. 27000.  7200.]
210000


##**Diapositiva 5**

###**Indexación, rebanado y máscaras**
#####La misma sintaxis de las listas, más una capacidad nueva: seleccionar con una condición.

In [ ]:
precios = np.array([24000, 28000, 22000, 30000, 8000])

precios[0]
precios[-1]
precios[1:4]

mascara = precios > 20000
precios[mascara]
precios[mascara].size

categoria = np.where(precios > 25000, "alto", "normal")

print(precios[0])
print(precios[-1])
print(precios[1:4])

print(mascara)
print(precios[mascara])
print(precios[mascara].size)
print(categoria.dtype)
print(categoria)


24000
8000
[28000 22000 30000]
[ True  True  True  True False]
[24000 28000 22000 30000]
4
<U6
['normal' 'alto' 'normal' 'alto' 'normal']


In [ ]:
#mascaras
# &: para Y; |para la condición "o"

mascara_2 = (precios > 5000) & (precios < 26000)
mascara_2
print(f"Resultado de la mascara #2:{mascara_2}")

mascara_3 = (precios > 5000) | (precios < 26000)
mascara_3
print(f"Resultado de la mascara #3:{mascara_3}")

print(precios)
print(precios[mascara_2])
print(precios[mascara_3])


Resultado de la mascara #2:[ True False  True False  True]
Resultado de la mascara #3:[ True  True  True  True  True]
[24000 28000 22000 30000  8000]
[24000 22000  8000]
[24000 28000 22000 30000  8000]


##**Diapositiva 6**

###**Agregar y resumir**
#####Las funciones de resumen colapsan el arreglo en un número, o en un número por fila o por columna.

In [ ]:
ingresos = np.array(
    [48000, 28000, 66000, 60000, 8000])

ingresos.sum()     # 210000
ingresos.mean()    # 42000.0
ingresos.max()     # 66000
ingresos.std()     # 21391.59

In [ ]:
matriz = np.array([[48000, 28000],
                   [66000, 60000],
                   [ 8000, 12000]])

matriz.sum()          # 222000
matriz.sum(axis=0)    # [122000 100000]
matriz.sum(axis=1)    # [76000 126000 20000]


array([ 76000, 126000,  20000])

##**Diapositiva 7**

###**De NumPy a pandas**
#####El arreglo resuelve el cálculo, pero no sabe que una columna se llama precio y otra producto.

In [ ]:
#Un primer DataFrame
#Aquí se crea dataframe de ejemplo.

#import numpy as np
import pandas as pd

serie = pd.Series([24000, 28000, 22000])     # serie en pandas
#arreglo_np = np.array([24000, 28000, 22000]) # arreglo en numpy

serie.to_numpy()            # array([24000, 28000, 22000])
print(serie)

df = pd.DataFrame({
    "producto": ["Bowl Andino", "Pasta Urbana"],
    "precio": [24000, 28000],
})

type(df["precio"].to_numpy())   # <class 'numpy.ndarray'>
#type(df.precio.to_numpy())   # <class 'numpy.ndarray'>

type(df) #metodo para mostrar el tipo de estructura de datos (arreglo np o DataFrame)

0    24000
1    28000
2    22000
dtype: int64


pandas.core.frame.DataFrame

##**Diapositiva 8**

###**¿Qué es un DataFrame?**
#####Varias columnas, cada una un arreglo con su propio tipo, compartiendo un índice que identifica las filas

In [ ]:
tabla = df[["producto", "cantidad"]]
type(tabla)      # pandas.core.frame.DataFrame
tabla.shape      # (16, 2)

KeyError: "['cantidad'] not in index"

##**Diapositiva 10**

###**Crear el DataFrame**
#####pd.DataFrame() recibe la lista de diccionarios y deduce las columnas de las claves.

In [ ]:
Fecha	Cliente ID	Producto	Categoría	Cantidad	Precio Unitario	Costo Unitario	Sede
3/08/2026	101	Bowl Andino	Almuerzo	2	24.000,00	14.000,00	centro
3/08/2026	102	Pasta Urbana	Almuerzo	1	28.000,00	17.000,00	NORTE
4/08/2026	103	Bowl Andino	Almuerzo	1	24.000,00	14.000,00	Centro

In [ ]:
datos_ventas = {"Fecha": ["3/08/2026","3/08/2026","4/08/2026"],
         "Cliente_ID": [101,102,103],
         "Producto": ["Bowl Andino","Pasta Urbana","Bowl Andino"],
         "Categoría": ["Almuerzo","Almuerzo","Almuerzo"],
         "Cantidad": [2,1,1],
         "Precio Unitario": [24000.00,28000.00,24000.00],
         "Costo Unitario": [14000.00,17000.00,14000.00],
         "Sede": ["centro","NORTE","Centro"]}


print(datos_ventas)


{'Fecha': ['3/08/2026', '3/08/2026', '4/08/2026'], 'Cliente_ID': [101, 102, 103], 'Producto': ['Bowl Andino', 'Pasta Urbana', 'Bowl Andino'], 'Categoría': ['Almuerzo', 'Almuerzo', 'Almuerzo'], 'Cantidad': [2, 1, 1], 'Precio Unitario': [24000.0, 28000.0, 24000.0], 'Costo Unitario': [14000.0, 17000.0, 14000.0], 'Sede': ['centro', 'NORTE', 'Centro']}


In [ ]:
import pandas as pd

df_ventas = pd.DataFrame(datos_ventas)
type(df_ventas)

#df_ventas["Precio Unitario"].sum()

df_ventas.head(1)




,Fecha,Cliente_ID,Producto,Categoría,Cantidad,Precio Unitario,Costo Unitario,Sede
0,3/08/2026,101,Bowl Andino,Almuerzo,2,24000.0,14000.0,centro
